# Basic Pytorch

### Construct 3x2 empty matrix

In [1]:
import torch

In [2]:
x = torch.empty(3,2)

In [3]:
x

tensor([[1.3567e-19, 6.6277e-10],
        [4.9120e-14, 1.3563e-19],
        [1.8578e-01, 4.7429e+30]])

### Construct 3x2 zeros matrix

In [4]:
y = torch.zeros(3,2)

In [5]:
y

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### Construct 3x2 ones matrix

In [6]:
z = torch.ones(3,2)

In [7]:
z

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

### Construct 3x2 rand matrix

In [8]:
a = torch.rand(3,2)

In [9]:
a

tensor([[0.1740, 0.3144],
        [0.3101, 0.1229],
        [0.0234, 0.6867]])

# Matrix addition

In [10]:
print(x+y)

tensor([[1.3567e-19, 6.6277e-10],
        [4.9120e-14, 1.3563e-19],
        [1.8578e-01, 4.7429e+30]])


In [11]:
print(torch.add(x,y))

tensor([[1.3567e-19, 6.6277e-10],
        [4.9120e-14, 1.3563e-19],
        [1.8578e-01, 4.7429e+30]])


In [12]:
result = torch.empty(3, 2)

In [13]:
torch.add(x, y, out=result)

tensor([[1.3567e-19, 6.6277e-10],
        [4.9120e-14, 1.3563e-19],
        [1.8578e-01, 4.7429e+30]])

In [14]:
result

tensor([[1.3567e-19, 6.6277e-10],
        [4.9120e-14, 1.3563e-19],
        [1.8578e-01, 4.7429e+30]])

In [15]:
y.add_(x)

tensor([[1.3567e-19, 6.6277e-10],
        [4.9120e-14, 1.3563e-19],
        [1.8578e-01, 4.7429e+30]])

In [16]:
y

tensor([[1.3567e-19, 6.6277e-10],
        [4.9120e-14, 1.3563e-19],
        [1.8578e-01, 4.7429e+30]])