# Basic Pytorch

### Construct 3x2 empty matrix

In [1]:
import torch

In [2]:
x = torch.empty(3,2)

In [3]:
x

tensor([[ 2.8026e-45,  0.0000e+00],
        [-5.8064e+17,  4.5916e-41],
        [-5.7643e+17,  4.5916e-41]])

### Construct 3x2 zeros matrix

In [5]:
y = torch.zeros(3,2)

In [6]:
y

tensor([[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]])

### Construct 3x2 ones matrix

In [7]:
z = torch.ones(3,2)

In [8]:
z

tensor([[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]])

### Construct 3x2 rand matrix

In [9]:
a = torch.rand(3,2)

In [10]:
a

tensor([[ 0.9182,  0.1682],
        [ 0.1825,  0.1346],
        [ 0.8360,  0.7336]])

# Matrix addition

In [14]:
print(x+y)

tensor([[ 2.8026e-45,  0.0000e+00],
        [-5.8064e+17,  4.5916e-41],
        [-5.7643e+17,  4.5916e-41]])


In [15]:
print(torch.add(x,y))

tensor([[ 2.8026e-45,  0.0000e+00],
        [-5.8064e+17,  4.5916e-41],
        [-5.7643e+17,  4.5916e-41]])


In [16]:
result = torch.empty(3, 2)

In [17]:
torch.add(x, y, out=result)

tensor([[ 2.8026e-45,  0.0000e+00],
        [-5.8064e+17,  4.5916e-41],
        [-5.7643e+17,  4.5916e-41]])

In [18]:
result

tensor([[ 2.8026e-45,  0.0000e+00],
        [-5.8064e+17,  4.5916e-41],
        [-5.7643e+17,  4.5916e-41]])

In [19]:
y.add_(x)

tensor([[ 2.8026e-45,  0.0000e+00],
        [-5.8064e+17,  4.5916e-41],
        [-5.7643e+17,  4.5916e-41]])

In [20]:
y

tensor([[ 2.8026e-45,  0.0000e+00],
        [-5.8064e+17,  4.5916e-41],
        [-5.7643e+17,  4.5916e-41]])